name: spelling

on:
  pull_request_target:
  push:
  issue_comment:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
  - name: Codespell action
      uses: plettich/python_codespell_action@v0.1

    
