name: Spell checking
on:
  pull_request_target:
  push:
  issue_comment:
    types: [created]

jobs:
  spelling:
  runs-on: ubuntu-latest
  steps:
    - name: install 
      run: python -m pip install codespell
    - name: run  
      run: codespell .
