name: NBCheckBot
on:
  pull_request:
jobs:  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - id: installrequirements
        shell: sh
        run: |
          python -m pip install --upgrade pip
          python -m pip install -e .
      - uses: "treebeardtech/nbmake-action@v0.2"
        with:
          path: "./examples"
          path-output: .
          notebooks: |
            'community/*.ipynb'
            'sevenbridges/*/*.ipynb'
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: |
           Hello @${{ github.actor }}, thank you for contributing to the CDA Community Notebook Library. CDA-bot has tried to run your notebook. If you got a green, we'll be running manual tests shortly. If you got a red X please check out the report in the "Some checks were not successful" above by clicking on the "Details" link next to nbcheckbot and fix any issues. 
          GITHUB_TOKEN: ${{ secrets.ALLTHEACTIONS }}
