name: NBCheckBot
on:
  pull_request:
jobs: check
  - uses: actions/checkout@v2
  - uses: actions/setup-python@v2
  - uses: "treebeardtech/nbmake-action@v0.2"
   with:
      path: "./examples"
     path-output: .
      notebooks: |
        'community/*.ipynb'
        'sevenbridges/*/*.ipynb'
