# This is a basic workflow to help you get started with Actions

name: Spellcheck Bot
# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  pull_request:

jobs:  
  build:
    
    # Check if the PR is not raised by this workflow and is not from a fork
    if: startsWith(github.head_ref, 'spelling/') == false && github.event.pull_request.head.repo.full_name == github.repository
    runs-on: ubuntu-latest
    outputs:
      erroutput: ${{ steps.spelling.outputs.test }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - id: spelling
        shell: sh
        run: |
          python -m pip install --upgrade pip
          python -m pip install codespell
          codespell || codespell -w && echo "::set-output name=test::65"
          
          
          
  fix:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ needs.build.outputs.erroutput == 65 }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: spellfix
        shell: sh
        run: |
          python -m pip install --upgrade pip
          python -m pip install codespell
          codespell -w
      - name: Set branch name
        id: vars
        run: echo ::set-output name=branch-name::"spelling/${{ github.head_ref }}"
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          token: ${{ secrets.ALLTHEACTIONS }}
          title: Auto Spell Check for ${{ github.head_ref }}
          base: ${{ github.head_ref }}
          labels: spelling
          branch: ${{ steps.vars.outputs.branch-name }}
          commit-message: Auto Spell Check
          body: |
            Hello @${{ github.actor }}, thank you for contributing to the CDA Community Notebook Library. Our bot has detected spelling errors in your submission. Please review it's suggested changes here. To accept the suggestions, merge this PR. To reject the suggestions, close this PR and make the necessary fixes in your original PR. 
      - name: Fail if codespell made changes
        run: exit 1

